version: '3.3'
services:
  db:
    container_name: pain-care-db
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'PainCare'
      MYSQL_USER: 'abdo'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'D0tPAJqubDOJzGh'
      MYSQL_ROOT_HOST: '%'
    ports:
      - '30001:3306'
    expose:
      - '3306'
      - '30001'
    volumes:
    - pain-care-db:/var/lib/mysql
    - ./src/main/java/Database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
  k6:
    image: grafana/k6
    volumes:
      - ./k6-scripts:/scripts
    depends_on:
      - server
  jaeger:
    image: jaegertracing/all-in-one:1.54
    container_name: jaeger
    ports:
      - "16686:16686"   # UI
      - "4318:4318"     # OTLP HTTP
      - "4317:4317"     # OTLP gRPC
  server:
    container_name: pain-care-server
    restart: always
    ports:
      - 8001:8080
    build:
      context: .
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4318
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
      - OTEL_SERVICE_NAME=PainCare
    volumes:
      - /app/webcontent/assets/avatars
      - /app/webcontent/assets/blogs-images
      - ./logs:/app/logs
    depends_on:
      - db
      - jaeger
  grafana:
    image: grafana/grafana
    container_name: pain-care-grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alert.rules.yml:/etc/prometheus/alert.rules.yml
volumes:
  pain-care-db:
  grafana-data:
  